// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Module.Contribuyente.Perfiles.Persistence.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Module.Contribuyente.Perfiles.Persistence.Migrations
{
    [DbContext(typeof(ContribuyenteDbContext))]
    [Migration("20250814164602_v_1_0_0_Contribuyentes_Migration")]
    partial class v_1_0_0_Contribuyentes_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Module.Contribuyente.Perfiles.Domain.Entities.PerfilContribuyente", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<DateTimeOffset>("CreadoEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RncCedula")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RncCedula")
                        .IsUnique();

                    b.HasIndex("Nombre", "Tipo");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Nombre", "Tipo"), "Btree");

                    b.ToTable("PerfilContribuyente", "contribuyentes");
                });
#pragma warning restore 612, 618
        }
    }
}
