// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modulo.Comprobante.Registros.Persistence.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modulo.Comprobante.Registros.Persistence.Migrations
{
    [DbContext(typeof(ComprobanteDbContext))]
    partial class ComprobanteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modulo.Comprobante.Registros.Domain.Entities.ComprobanteRegistro", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<DateTimeOffset>("CreadoEnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Itbis18")
                        .HasPrecision(16, 2)
                        .HasColumnType("numeric(16,2)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(16, 2)
                        .HasColumnType("numeric(16,2)");

                    b.Property<string>("NCF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("PerfilContribuyenteId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilContribuyenteId", "NCF", "Monto");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("PerfilContribuyenteId", "NCF", "Monto"), "Btree");

                    b.ToTable("ComprobanteRegistro", "comprobantes");
                });
#pragma warning restore 612, 618
        }
    }
}
