// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Module.Internal.Error.Logs.Persistence.CompiledEntities
{
    public partial class ErrorLogDbContextModel
    {
        private ErrorLogDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("32a47522-c33a-4842-a34c-88f29c0edf82"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var errorLog = ErrorLogEntityType.Create(this);

            ErrorLogEntityType.CreateAnnotations(errorLog);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.8");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
