// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Module.Internal.Error.Logs.Persistence.CompiledEntities;
using Module.Internal.Error.Logs.Persistence.Context;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ErrorLogDbContext), typeof(ErrorLogDbContextModel))]
