// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Modulo.Comprobante.Registros.Persistence.Context;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Modulo.Comprobante.Registros.Persistence.CompiledEntities
{
    [DbContext(typeof(ComprobanteDbContext))]
    public partial class ComprobanteDbContextModel : RuntimeModel
    {
        private static readonly bool _useOldBehavior31751 =
            System.AppContext.TryGetSwitch("Microsoft.EntityFrameworkCore.Issue31751", out var enabled31751) && enabled31751;

        static ComprobanteDbContextModel()
        {
            var model = new ComprobanteDbContextModel();

            if (_useOldBehavior31751)
            {
                model.Initialize();
            }
            else
            {
                var thread = new System.Threading.Thread(RunInitialization, 10 * 1024 * 1024);
                thread.Start();
                thread.Join();

                void RunInitialization()
                {
                    model.Initialize();
                }
            }

            model.Customize();
            _instance = (ComprobanteDbContextModel)model.FinalizeModel();
        }

        private static ComprobanteDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
