// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Modulo.Comprobante.Registros.Persistence.CompiledEntities
{
    public partial class ComprobanteDbContextModel
    {
        private ComprobanteDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("b15982ff-a99c-4c39-95d5-78ce3de090ed"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var comprobanteRegistro = ComprobanteRegistroEntityType.Create(this);

            ComprobanteRegistroEntityType.CreateAnnotations(comprobanteRegistro);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.8");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
