// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Modulo.Comprobante.Registros.Persistence.CompiledEntities;
using Modulo.Comprobante.Registros.Persistence.Context;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ComprobanteDbContext), typeof(ComprobanteDbContextModel))]
