// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Module.Contribuyente.Perfiles.Persistence.CompiledEntities;
using Module.Contribuyente.Perfiles.Persistence.Context;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ContribuyenteDbContext), typeof(ContribuyenteDbContextModel))]
