// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Module.Contribuyente.Perfiles.Persistence.CompiledEntities
{
    public partial class ContribuyenteDbContextModel
    {
        private ContribuyenteDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("d10b2818-ab7a-4f10-bfcf-2c3f653e151f"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var perfilContribuyente = PerfilContribuyenteEntityType.Create(this);

            PerfilContribuyenteEntityType.CreateAnnotations(perfilContribuyente);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.8");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
