// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Module.Contribuyente.Perfiles.Persistence.Context;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Module.Contribuyente.Perfiles.Persistence.CompiledEntities
{
    [DbContext(typeof(ContribuyenteDbContext))]
    public partial class ContribuyenteDbContextModel : RuntimeModel
    {
        private static readonly bool _useOldBehavior31751 =
            System.AppContext.TryGetSwitch("Microsoft.EntityFrameworkCore.Issue31751", out var enabled31751) && enabled31751;

        static ContribuyenteDbContextModel()
        {
            var model = new ContribuyenteDbContextModel();

            if (_useOldBehavior31751)
            {
                model.Initialize();
            }
            else
            {
                var thread = new System.Threading.Thread(RunInitialization, 10 * 1024 * 1024);
                thread.Start();
                thread.Join();

                void RunInitialization()
                {
                    model.Initialize();
                }
            }

            model.Customize();
            _instance = (ContribuyenteDbContextModel)model.FinalizeModel();
        }

        private static ContribuyenteDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
