// <auto-generated />
using System;
using System.Reflection;
using Global.Sources.ValueObjects.Converters;
using Global.Sources.ValueObjects.Values;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Module.Contribuyente.Perfiles.Domain.Entities;
using Module.Contribuyente.Perfiles.Domain.Enums;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Module.Contribuyente.Perfiles.Persistence.CompiledEntities
{
    [EntityFrameworkInternal]
    public partial class PerfilContribuyenteEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Module.Contribuyente.Perfiles.Domain.Entities.PerfilContribuyente",
                typeof(PerfilContribuyente),
                baseEntityType,
                propertyCount: 6,
                unnamedIndexCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(UlidObject),
                propertyInfo: typeof(PerfilContribuyente).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfilContribuyente).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                maxLength: 26,
                valueConverter: new UlidObjectConverter());
            id.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var creadoEnUtc = runtimeEntityType.AddProperty(
                "CreadoEnUtc",
                typeof(DateTimeOffset),
                propertyInfo: typeof(PerfilContribuyente).GetProperty("CreadoEnUtc", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfilContribuyente).GetField("<CreadoEnUtc>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));
            creadoEnUtc.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var estaActivo = runtimeEntityType.AddProperty(
                "EstaActivo",
                typeof(BooleanObject),
                propertyInfo: typeof(PerfilContribuyente).GetProperty("EstaActivo", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfilContribuyente).GetField("<EstaActivo>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new BooleanObjectConverter());
            estaActivo.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var nombre = runtimeEntityType.AddProperty(
                "Nombre",
                typeof(StringObject),
                propertyInfo: typeof(PerfilContribuyente).GetProperty("Nombre", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfilContribuyente).GetField("<Nombre>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 100,
                valueConverter: new StringObjectConverter());
            nombre.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var rncCedula = runtimeEntityType.AddProperty(
                "RncCedula",
                typeof(StringObject),
                propertyInfo: typeof(PerfilContribuyente).GetProperty("RncCedula", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfilContribuyente).GetField("<RncCedula>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 11,
                valueConverter: new StringObjectConverter());
            rncCedula.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var tipo = runtimeEntityType.AddProperty(
                "Tipo",
                typeof(IdentityType),
                propertyInfo: typeof(PerfilContribuyente).GetProperty("Tipo", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(PerfilContribuyente).GetField("<Tipo>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            tipo.SetSentinelFromProviderValue(0);
            tipo.AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { rncCedula },
                unique: true);

            var index0 = runtimeEntityType.AddIndex(
                new[] { nombre, tipo });

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", "contribuyentes");
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "PerfilContribuyente");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
